// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypvgccslibbvaichwnbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdmdjY3NsaWJidmFpY2h3bmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NjM2NzUsImV4cCI6MjA4ODIzOTY3NX0.ln5XLpioGye9fQajSbGsWXM_cQSEcnt3tTakncC44_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});